/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package busboard;

import busboard.BusStopFinder.BusStopFinder;

public class App {

    public static void main(String[] args) {
        new BusStopFinder().getter();
    }
}
